all: ispointinsidetriangle huffmandecoder firstrepeatedwordinsentence pathstogoal intersection_r1 myoptional_r2

ispointinsidetriangle: ispointinsidetriangle.cpp Makefile
	g++ -O0 -g3 $@.cpp -o $@

huffmandecoder: huffmandecoder.cpp Makefile
	g++ -O0 -g3 $@.cpp -o $@

firstrepeatedwordinsentence: firstrepeatedwordinsentence.cpp Makefile
	g++ -O0 -g3 $@.cpp -o $@

pathstogoal: pathstogoal.cpp Makefile
	g++ -O0 -g3 $@.cpp -o $@

intersection_r1: intersection_r1.cpp Makefile
	g++ -O0 -g3 $@.cpp -o $@

myoptional_r2: myoptional_r2.cpp Makefile
	g++ -O0 -g3 $@.cpp -o $@

clean:
	rm -f *.out ispointinsidetriangle huffmandecoder firstrepeatedwordinsentence pathstogoal intersection_r1 myoptional_r2
