all: runningmedian queuefrom2stacks

runningmedian: runningmedian.cpp Makefile
	g++ -O4 -g0 runningmedian.cpp -o runningmedian

queuefrom2stacks: queuefrom2stacks.cpp Makefile
	g++ -O4 -g0 queuefrom2stacks.cpp -o queuefrom2stacks

clean:
	rm -f runningmedian queuefrom2stacks *.out
