all:	problem1 problem2 problem3 problem4
clean:
	rm -f bin/*
problem1:
	mkdir -p bin; g++ -std=c++14 -o bin/problem1 problem1.cpp
problem2:
	mkdir -p bin; g++ -std=c++14 -o bin/problem2 problem2.cpp
problem3:
	mkdir -p bin; g++ -std=c++14 -o bin/problem3 problem3.cpp
problem4:
	mkdir -p bin; g++ -std=c++14 -o bin/problem4 problem4.cpp
