/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techolution */

#ifndef _Included_com_techolution
#define _Included_com_techolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techolution
 * Method:    assignment
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_techolution_assignment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
